### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yhamoudi** [yhamoudi/Shape-Indexing#6]
- [x] Enlever les morceaux de code qui ne sont pas expliqués dans le rapport/utilisés dans le programme final
  - [x] Finir rapport
  - [x] Compléter Readme
  - [x] Ajouter 2 scripts (cf les scripts bash `sound` et `sound_game`) : 
    - le premier prend deux images en entrée et retourne une « distance » sur la sortie std.
    - le second prend une image en entrée et retourne, pour chaque classe de la BdD, une probabilité d’appartenance (un scalaire entre 0 et 100 par ligne, —une ligne==une classe—). Ordre : https://github.com/dcoeurjo/lectureDG/blob/master/assignments/ShapeIndexing/classes.csv
  - [x] Mettre les paramètres définitifs là où il faut (descripteur, distance, ...) (ev3.db ? > classification.sh)
  - [ ] Archive finale : lorsque l'archive est décompressée, elle doit produire un dossier. Enlever

**Comment by yhamoudi** [comment]
Le dépôt est passé en public

**Comment by yhamoudi** [comment]
Je crois qu'il manque encore tes images dans le dépôt (pour le rapport)

**Comment by yhamoudi** [comment]
J'ai ajouté dans le readme un lien pour télécharger eigenvalues.db, dis-moi si tu réussis à y accéder

**Comment by yhamoudi** [comment]
ton équation (1) doit avoir un problème (∆f − w^2/v^2)

**Comment by robocop** [comment]
Il y a un truc encore qui n'est pas expliqué dans le rapport : comment on calcule le vecteur des probabilités pour la classification.

Actuellement, ce que je fais (et c'est discutable) : je regarde pour chacune des 70 classes l'image de la classe la plus proche à l'image à classifier.

Ceci me donne 70 distances, que je multiplie par une constante pour obtenir un vecteur de somme égale à 1.

Je ne sais pas trop ou rajouter ça dans le rapport, mais il faut le faire :)

**Comment by yhamoudi** [comment]
J'ai modifié un peu la structure du rapport. Tu peux l'ajouter dans la section 2.4 "Calcul du descripteur associé aux valeurs propres"

**Comment by yhamoudi** [comment]
c'est correct de dire similarité = 1 - cosine/2 ? (cosine est entre -1 et 1 donc 1 - cosine/2 entre 0.5 et 1.5).

C'est pas plutôt (1-cosine)/2 ?

**Comment by robocop** [comment]
Ha: je pensais cosine = distance_cosinus telle qu'implémentée dans scipy.
Dans ce cas, similarité(a,b) = 1-distance_cosine(a, b)/2 = (1+a . b / ||a|| || b || )/2

**Comment by yhamoudi** [comment]
> Il y a un truc encore qui n'est pas expliqué dans le rapport : comment on calcule le vecteur des probabilités pour la classification.

Je suis en train de l'ajouter

**Comment by robocop** [comment]
Cool, merci :)

**Comment by yhamoudi** [comment]
> Dans ce cas, similarité(a,b) = 1-distance_cosine(a, b)/2 = (1+a . b / ||a|| || b || )/2

ah oui, exact

**Comment by yhamoudi** [comment]
> Ceci me donne 70 distances, que je multiplie par une constante pour obtenir un vecteur de somme égale à 1.

Mais du coup à la fin : valeur élevée = distance élevée = peu similaires (alors qu'on veut proche de 1 = très similaires) ?

**Comment by robocop** [comment]
Ha oui pardon, du coup je prenais l'inverse de la distance ;)

**Comment by robocop** [comment]
Et si une distance est nulle, par exemple si la distance à la classe c est nulle, je dis que on a c avec proba 1, les autres avec proba 0. C'est un peu moche mais ça me semblait logique

**Comment by yhamoudi** [comment]
voilà, tu peux relire :)
(j'ai ajouté ton truc dans la conclusion, il y a aussi une remarque en rouge dans le pdf, je peux l'enlever ?)

**Comment by yhamoudi** [comment]
> il y a aussi une remarque en rouge dans le pdf, je peux l'enlever ?

ah non, tu l'avais enlevé, c'est bon :)

**Comment by yhamoudi** [comment]
c'est bon pour moi, rien à changer

**Comment by robocop** [comment]
C'est parfait, on envoie ;) ?

**Comment by robocop** [comment]
Je te laisse le grand honneur d'envoyer, je file au karaté ;)

**Comment by yhamoudi** [comment]
J'ai ajouté une archive dans le dépôt, décompresse-là et regarde que tout est bon

**Comment by yhamoudi** [comment]
ok, c'est parti :)

**Comment by robocop** [comment]
Félicitation à nous, ce fut du bon travail ;)
